// Generated by gencpp from file sub_message/SubMessageRequest.msg
// DO NOT EDIT!


#ifndef SUB_MESSAGE_MESSAGE_SUBMESSAGEREQUEST_H
#define SUB_MESSAGE_MESSAGE_SUBMESSAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sub_message
{
template <class ContainerAllocator>
struct SubMessageRequest_
{
  typedef SubMessageRequest_<ContainerAllocator> Type;

  SubMessageRequest_()
    : opperation()
    , direction()
    , distance(0)
    , sent_time()  {
    }
  SubMessageRequest_(const ContainerAllocator& _alloc)
    : opperation(_alloc)
    , direction(_alloc)
    , distance(0)
    , sent_time()  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _opperation_type;
  _opperation_type opperation;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direction_type;
  _direction_type direction;

   typedef int64_t _distance_type;
  _distance_type distance;

   typedef ros::Time _sent_time_type;
  _sent_time_type sent_time;




  typedef boost::shared_ptr< ::sub_message::SubMessageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sub_message::SubMessageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SubMessageRequest_

typedef ::sub_message::SubMessageRequest_<std::allocator<void> > SubMessageRequest;

typedef boost::shared_ptr< ::sub_message::SubMessageRequest > SubMessageRequestPtr;
typedef boost::shared_ptr< ::sub_message::SubMessageRequest const> SubMessageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sub_message::SubMessageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sub_message::SubMessageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sub_message

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sub_message::SubMessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sub_message::SubMessageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sub_message::SubMessageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sub_message::SubMessageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sub_message::SubMessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sub_message::SubMessageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sub_message::SubMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2421f828b0652a589c949370ff4f040";
  }

  static const char* value(const ::sub_message::SubMessageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2421f828b0652a5ULL;
  static const uint64_t static_value2 = 0x89c949370ff4f040ULL;
};

template<class ContainerAllocator>
struct DataType< ::sub_message::SubMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sub_message/SubMessageRequest";
  }

  static const char* value(const ::sub_message::SubMessageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sub_message::SubMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string opperation\n\
string direction\n\
int64 distance\n\
time sent_time\n\
";
  }

  static const char* value(const ::sub_message::SubMessageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sub_message::SubMessageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.opperation);
      stream.next(m.direction);
      stream.next(m.distance);
      stream.next(m.sent_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SubMessageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sub_message::SubMessageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sub_message::SubMessageRequest_<ContainerAllocator>& v)
  {
    s << indent << "opperation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.opperation);
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direction);
    s << indent << "distance: ";
    Printer<int64_t>::stream(s, indent + "  ", v.distance);
    s << indent << "sent_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.sent_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUB_MESSAGE_MESSAGE_SUBMESSAGEREQUEST_H
